### ISSUE TITLE
`define with inline comment

### ISSUE THREAD

**Issue by tux3** [dalance/sv-parser#12]
If a \`define has a C++ style inline comment, sv-parser treats it as part of the value:

```
`define NAME 42 // Comment
```

This results in a parse error when the define is used in a parameter:

```
interface foo #(WIDTH = `NAME) ();
endinterface
```

Other tools seem to ignore the comment and accept the define.

**Comment by dalance** [comment]
Thank you for your information, and sorry for the late reply.
I fixed this issue.

**Comment by tux3** [comment]
Thank you!
