### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by slayer152** [dalance/sv-parser#19]
Thank you for this awesome project. I was wondering if  the following either or both of the following features can be supported:

- `define tokens can be added to the syntax tree. I would like to use your parser to generate tag files (SV support in universal-ctags is inadequate).

[https://github.com/google/verible] project supports this feature.

E.g. Verible output producing a `define token 

```
Parse Tree:
Node (tag: kDescriptionList) {
  Node (tag: kPreprocessorDefine) {
    (#"`define" @4-11: "`define")
    (#PP_Identifier @12-16: "ABCD")
    (#"<<`define-tokens>>" @17-18: "1")
  }
...
....
```

-  Support an option to return the incomplete syntax tree even if there are syntax errors

Thanks again!

**Comment by dalance** [comment]
Sorry for late reply.
I added the following features and released v0.9.0.

* Add define tokens to syntax tree
* Add `allow_incomplete` option to `parse_sv` / `parse_lib`
