### ISSUE TITLE
Parse error bug

### ISSUE THREAD

**Issue by Kostal0117** [dalance/sv-parser#75]
{"jsonrpc":"2.0","error":{"code":-32700,"message":"Parse error"}

This bug appeaes when i use snap to install svls, and use "svls" in terminal.

**Comment by DaveMcEwan** [comment]
@Kostal0117 Can you provide a testcase so we can reproduce the problem? I suspect you just have a syntax error in your code.

**Comment by DaveMcEwan** [comment]
@dalance I think this can be safely closed.
